name: CI

on:
  push:
    branches:
      - 'master'   # Push events on master branch

jobs:
  rebuild:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: cd src && rm node_modules -Rf && npm i
      - run: cd src && npm run build
      - name: Commit and push built
        run: |
          git config --global user.name 'Lawrence Cherone'
          git config --global user.email 'lcherone@users.noreply.github.com'
          git add -A ./
          git commit -am "Automated rebuild" || echo "Nothing to commit"
          git push

