name: CI

on:
  push:
    branches:
      - 'master'   # Push events on master branch

jobs:
  rebuild:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Rebuild app then push
        run: date +%s > report.txt
      - name: Commit report
        run: |
          git config --global user.name 'Lawrence Cherone'
          git config --global user.email 'lcherone@users.noreply.github.com'
          git add -A ./
          git commit -am "Automated report"
          git push

